from evdev.ecodes import *

keydict = {
        'a': KEY_A,
        'b': KEY_B,
        'c': KEY_C,
        'd': KEY_D,
        'e': KEY_E,
        'f': KEY_F,
        'g': KEY_G,
        'h': KEY_H,
        'i': KEY_I,
        'j': KEY_J,
        'k': KEY_K,
        'l': KEY_L,
        'm': KEY_M,
        'n': KEY_N,
        'o': KEY_O,
        'p': KEY_P,
        'q': KEY_Q,
        'r': KEY_R,
        's': KEY_S,
        't': KEY_T,
        'u': KEY_U,
        'v': KEY_V,
        'w': KEY_W,
        'x': KEY_X,
        'y': KEY_Y,
        'z': KEY_Z,
        }
